#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#define LEFT_FRONT_MOTOR 3
#define RIGHT_FRONT_MOTOR 4
#define LEFT_REAR_MOTOR 1//8
#define RIGHT_REAR_MOTOR 2//7

#define CAMERA_TILT 6
#define CAMERA_ROTATE 6
#define RIGHT_PICKER 7
#define LEFT_PICKER 8
#define PICKER_HOLDER 9


#define CATAPULT_LOCKER 1
#define CATAPULT_SCREW_MOTOR 5



#define CATAPULT_CEILING_SWITCH 5
#define CATAPULT_FLOOR_SWITCH 6


#define CATAPULT_ENCODER 3


#define GYRO 1

#endif
